[system]
sudo
lightdm
sway
swaybg
acpi
alsa-utils
network-manager
curl
gpg
wget
tee
swaylock

[applications]
keepassxc
brightnessctl
alacritty
rsync
lf
unzip
htop
zsh
# texlive-full
floorp
rofi
vscode

# dropbox
# obsidian
#swaync
#hyprlock
