[system]
sudo
lightdm
sway
swaybg
acpi
alsa-utils
network-manager
curl
gpg
wget
tee

[applications]
keepassxc
brightnessctl
alacritty
rsync
lf
unzip
htop
zsh
# texlive-full

floorp
rofi
#vscode
# dropbox
# discord
# mattermost-desktop
# obsidian
#swaync
#hyprlock
#beekeeper
#strongswan
