[system]
sudo
lightdm
sway
swaybg
acpi
alsa-utils
network-manager
curl

[applications]
keepassxc
brightnessctl
alacritty
rsync
lf
unzip
htop
# texlive-full

#floorp
rofi
#vscode
# dropbox
# discord
# mattermost-desktop
# obsidian
#swaync
zsh
#hyprlock
#beekeeper
#strongswan
